def transformer(): pass
def music_knowledge(): pass
def contrastive(): pass
def hierarchical(): pass
def generation(): pass
def structure(): pass
def relation(): pass
def psychology(): pass
def education(): pass
